os: linux
dist: trusty
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/.yarn
before_script:
  - sudo sysctl -w vm.max_map_count=262144
script:
  - mvn compile || travis_terminate 1;
  - mvn -B -Dmaven.test.skip=true package || travis_terminate 1;
  - ls -la graylog2-server/target
after_success:
  - mvn -B -Dmaven.test.skip=true -Dskip.web.build=true assembly:single || travis_terminate 1;
deploy:
  provider: script
  skip_cleanup: true
  script: bash docker_push.sh
  on:
    branch: image-builder

env:
  matrix:
  - GRAYLOG_ELASTICSEARCH_VERSION=5
